version : '3.7'
#networks:
#  hy-net:
#    external: true
services:
  zabbix-server:
        container_name : zabbix-server
        hostname: zabbixserver
        networks:
          hy-net:
        image: registry.cn-hangzhou.aliyuncs.com/yangyuanpeng/zabbix:ubuntu-3.4.13-server-mysql
        volumes:
          - /etc/localtime:/etc/localtime:ro
        ports :
          - 10051:10051
        restart: on-failure
        environment:
          TZ: Asia/Shanghai
          DB_SERVER_HOST : "192.168.200.211"
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER : 'zabbix'    #用户
          MYSQL_PASSWORD : "zabbix"
        ports :
          - 10051:10051
  zabbix-web:
        container_name : zabbix-web
        image: registry.cn-hangzhou.aliyuncs.com/yangyuanpeng/zabbix:ubuntu-3.4.13-web-nginx
#        networks:
#          hy-net:
        volumes:
          - /etc/localtime:/etc/localtime:ro
        ports :
          - 88:80
          - 8443:443
        restart: on-failure
        links :
          - zabbix-server:zabbix-server
        environment:
          TZ: Asia/Shanghai
          DB_SERVER_HOST : "192.168.200.211"
          MYSQL_USER : 'zabbix'
          MYSQL_DATABASE: "zabbix"
          MYSQL_PASSWORD : "zabbix"
          ZBX_SERVER_HOST : "zabbix-server"
          PHP_TZ: "Asia/Shanghai"

